### ISSUE TITLE
Error with "detail = TRUE" parameter in otp_get_times()

### ISSUE THREAD

**Issue by jamiedeweese** [marcusyoung/otpr#10]
**Describe the bug**
When setting the parameter detail to "detail = TRUE" I get the following error:

Error in `[.data.frame`(x, r, vars, drop = drop) : 
  undefined columns selected

**To Reproduce**
1. Load data that accompanies the tutorial "intro_otp.pdf" and follow all steps.
2. Attempt to run the following code:

otp_get_times(
  otpcon,
  fromPlace = c(53.48805,-2.24258),
  toPlace = c(53.36484,-2.27108),
  mode = "TRANSIT",
  date = "04-29-2020",
  time = "07:15:00",
  detail = TRUE
)
4. It generates an error: Error in `[.data.frame`(x, r, vars, drop = drop) : 
  undefined columns selected

5. If I remove the "detail = " parameter, I get no error and it generates the correct response:

otp_get_times(
  otpcon,
  fromPlace = c(53.48805,-2.24258),
  toPlace = c(53.36484,-2.27108),
  mode = "TRANSIT",
  date = "04-29-2020",
  time = "07:15:00"
)

$errorId
[1] "OK"

$duration
[1] 42.2

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Safari
 - R: 4.0

**Comment by marcusyoung** [comment]
@jamiedeweese Hi thanks for the report. I think this has been fixed in v0.4.1 (now on cran). Could you update the package and let me know?

**Comment by marcusyoung** [comment]
Confirmed this query runs fine with 0.4.1. Tested on tutorial data.

```
> library(otpr)
> otpcon <- otp_connect()
http://localhost:8080/otp is running OTPv1
Router http://localhost:8080/otp/routers/default exists
> otp_get_times(
+   otpcon,
+   fromPlace = c(53.48805,-2.24258),
+   toPlace = c(53.36484,-2.27108),
+   mode = "TRANSIT",
+   date = "04-29-2020",
+   time = "07:15:00",
+   detail = TRUE
+ )
$errorId
[1] "OK"

$itineraries
                start                 end      timeZone duration walkTime
1 2020-04-29 07:37:31 2020-04-29 08:19:43 Europe/London     42.2     5.17
  transitTime waitingTime transfers
1          37        0.03         0

$query
[1] "http://localhost:8080/otp/routers/default/plan?fromPlace=53.48805,-2.24258&toPlace=53.36484,-2.27108&mode=TRANSIT,WALK&date=04-29-2020&time=07:15:00&maxWalkDistance=800&walkReluctance=2&arriveBy=FALSE&transferPenalty=0&minTransferTime=0"
```

**Comment by jamiedeweese** [comment]
Thanks, Marcus!  Apologies for the delay.  I was offline for a few days unexpectedly.  I can confirm (as well) that it's working.  Thanks again.
