### ISSUE TITLE
get_isochrone function limited to Walk, Bus, Rail, Tram, Subway, and Transit. 

### ISSUE THREAD

**Issue by joekaylor** [marcusyoung/otpr#15]
when attempting to run otp_get_isochrone for bicycle catchments, I get the following error: * Variable 'mode': Must be element of set {'WALK','BUS','RAIL','TRAM','SUBWAY','TRANSIT'}, but is
 * 'BICYCLE'.

This used to have Car and Bicycle.

**Comment by marcusyoung** [comment]
@joekaylor It's not included as isochrones produced by OTP for car or bicycle or walk alone are not correct. The function within OTP is only intended for WALK and TRANSIT (together). See: https://groups.google.com/g/opentripplanner-users/c/BJSsrHJfHj4/m/suZySyojAQAJ
