### ISSUE TITLE
Get distance with transit 

### ISSUE THREAD

**Issue by orlandombaa** [marcusyoung/otpr#6]
Hello 

I have a question. Watching the documentation of the library I see that there is a difference in the available modes within the function `otp_get_distance` and `otp_get_times`.   

Is there possible to use TRANSIT in the function otp_get_distance? 

Best regards, 
Orlando

**Comment by marcusyoung** [comment]
Hi,

Distance can only be obtained for modes that use the street and path network. Distance is not available for transit modes. This information is not part of the GTFS specification and isn't normally relevant to the transit user.
